Repository ZenBit-Tech/ctrlchamps_fe, pull requests merged in 2023-12, with the labels that each got.

#37 F&B: Created main RTK requests for complete profile page
  src/components/profile/bio/Bio.tsx
  src/redux/api/accountVerificationAPI.ts
  src/redux/api/profileCompleteApi.ts
  src/redux/api/routes.ts
  src/redux/store.ts
  src/routes/index.ts
Labels: enhancement

#38 B&F Compete Profile 5 (Rate)
  src/components/complete-profile-fifth/CompleteProfileFifth.tsx
  src/components/login-form/LoginForm.tsx
  src/pages/profile/index.tsx
Labels: enhancement

#39 F&B complete profile 3 (Services)
  src/components/complete-profile-third/CompleteProfileThird.tsx
  src/components/complete-profile-third/constants.ts
  src/components/complete-profile-third/hooks.ts
  src/components/complete-profile-third/types.ts
  src/pages/profile/index.tsx
  src/redux/rootReducer.ts
  src/redux/slices/servicesSlice.ts
  src/redux/store.ts
Labels: enhancement

#45 feat: create appointment schedule components
  src/components/create-appointment/AppointmentScheduling.tsx
  src/components/create-appointment/AppointmentType.tsx
  src/components/create-appointment/OneTimeAppointment.tsx
  src/components/create-appointment/RecurringAppointment.tsx
  src/components/create-appointment/constants.ts
  src/components/create-appointment/styles.ts
  src/components/create-appointment/types.ts
  src/components/create-appointment/useShowDuration.tsx
  src/components/modal-cancel-appointment/CancelAppointmentModal.tsx
  src/components/modal-cancel-appointment/index.tsx
  src/components/modal-cancel-appointment/useCancelAppointmentModal.tsx
  src/constants/types.ts
  src/locales/langs/en.ts
  src/pages/create-appointment/index.tsx
  src/redux/rootReducer.ts
  src/redux/slices/appointmentSlice.ts
  src/redux/store.ts
  src/utils/calculateTimeDifference.ts
  src/utils/defineCustomTime.ts
Labels: good first issue

#42 feat: connect profile availability with backend
  src/components/complete-profile-fourth/CompleteProfileFourth.tsx
  src/components/complete-profile-fourth/constants.ts
  src/constants/index.ts
  src/redux/slices/availableDaysSlice.ts
  src/utils/generateTime.ts
Labels: good first issue

#41 Bug fix: sign up 2 form
  src/components/sign-up-second/constants.ts
  src/components/sign-up-second/hooks.ts
  src/components/sign-up-second/index.tsx
  src/components/sign-up-second/validation.ts
  src/constants/index.ts
  src/locales/langs/en.ts
  src/pages/sign-up/index.tsx
Labels: enhancement

#46 feat: finish profile page
  src/components/complete-profile-fifth/CompleteProfileFifth.tsx
  src/components/complete-profile-fourth/CompleteProfileFourth.tsx
  src/components/complete-profile-fourth/styles.ts
  src/components/complete-profile-second/work-form/WorkForm.tsx
  src/components/complete-profile-third/CompleteProfileThird.tsx
  src/components/profile/profile-qualification/certificate-form/CertificateForm.tsx
  src/components/reusable/profile-btn/ProfileBtn.tsx
  src/components/reusable/profile-btn/styles.ts
  src/components/reusable/profile-wrapper/styles.ts
  src/pages/profile/index.tsx
Labels: good first issue

#54 refactor: recurring appointment logic data fix
  src/components/create-appointment/AppointmentType.tsx
  src/components/create-appointment/RecurringAppointment.tsx
  src/components/create-appointment/constants.ts
  src/components/create-appointment/styles.ts
Labels: enhancement

#51 feat: create confirm appointment step
  src/assets/icons/ArrowForward.tsx
  src/assets/icons/Check.tsx
  src/assets/icons/CreditCardIcon.tsx
  src/assets/icons/EditIcon.tsx
  src/components/confirm-appointment/ConfirmAppointment.tsx
  src/components/confirm-appointment/Modal.tsx
  src/components/confirm-appointment/TasksList.tsx
  src/components/confirm-appointment/constants.ts
  src/components/confirm-appointment/style.ts
  src/components/confirm-appointment/types.ts
  src/components/reusable/modal/styles.ts
  src/locales/langs/en.ts
  src/theme/fonts.ts
Labels: good first issue

#57 fix: fix appointment bugs and logic
  src/components/create-appointment/AppointmentType.tsx
  src/components/create-appointment/RecurringAppointment.tsx
  src/locales/langs/en.ts
Labels: bug

#50 Bug fix: sign up 2 phone input
  src/components/sign-up-second/constants.ts
  src/components/sign-up-second/index.tsx
  src/components/sign-up-second/validation.ts
  src/locales/langs/en.ts
Labels: enhancement

#60 fix: bio step input
  src/components/profile/bio/Bio.tsx
Labels: enhancement

#65 fix: updated common styles of Complete profile
  src/components/complete-profile-fifth/CompleteProfileFifth.tsx
  src/components/complete-profile-fourth/CompleteProfileFourth.tsx
  src/components/complete-profile-second/CompleteProfileSecond.tsx
  src/components/complete-profile-second/work-form/WorkForm.tsx
  src/components/complete-profile-second/work-form/styles.ts
  src/components/complete-profile-second/work-list/WorkList.tsx
  src/components/complete-profile-third/CompleteProfileThird.tsx
  src/components/complete-profile-third/types.ts
  src/components/profile/bio/Bio.tsx
  src/components/profile/profile-qualification/certificate-form/CertificateForm.tsx
  src/components/profile/profile-qualification/certificate-form/styles.ts
  src/components/reusable/profile-btn/ProfileBtn.tsx
  src/components/reusable/profile-btn/styles.ts
  src/locales/langs/en.ts
  src/pages/profile/index.tsx
Labels: enhancement

#61 refactor: refactor time functionality
  src/components/complete-profile-fourth/CompleteProfileFourth.tsx
  src/components/complete-profile-fourth/constants.ts
  src/components/complete-profile-fourth/hooks.ts
  src/components/complete-profile-fourth/styles.ts
  src/components/complete-profile-fourth/types.ts
  src/components/create-appointment/AppointmentScheduling.tsx
  src/components/create-appointment/AppointmentType.tsx
  src/components/create-appointment/OneTimeAppointment.tsx
  src/components/create-appointment/RecurringAppointment.tsx
  src/components/create-appointment/constants.ts
  src/components/create-appointment/styles.ts
  src/locales/langs/en.ts
  src/utils/calculateTimeDifference.ts
  src/utils/defineCustomTime.ts
  src/utils/extractTimeFromDate.ts
  src/utils/generateTime.ts
Labels: enhancement

#66 Feat: FE Appointments page
  src/components/appointments/Appointments.tsx
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/appointment-drawer/styles.ts
  src/components/appointments/appointment-status/AppointmentStatus.tsx
  src/components/appointments/appointment-status/styles.ts
  src/components/appointments/appointments-list/AppointmentsList.tsx
  src/components/appointments/appointments-list/styles.ts
  src/components/appointments/cancel-modal/CancelModal.tsx
  src/components/appointments/cancel-modal/styles.ts
  src/components/appointments/constants.ts
  src/components/appointments/helpers.ts
  src/components/appointments/styles.ts
  src/components/appointments/types.ts
  src/constants/index.ts
  src/locales/langs/en.ts
  src/pages/index.tsx
  src/theme/colors.ts
  src/theme/fonts.ts
Labels: good first issue

#67 feat: connect appoitments page to backend
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/appointments-list/AppointmentsList.tsx
  src/components/appointments/cancel-modal/CancelModal.tsx
  src/components/appointments/constants.ts
  src/components/appointments/helpers.ts
  src/components/appointments/types.ts
  src/components/health-questionnaire/steps/SecondStepItem.tsx
  src/components/health-questionnaire/steps/Step1.tsx
  src/components/health-questionnaire/steps/Step2.tsx
  src/components/health-questionnaire/steps/Step3.tsx
  src/components/profile/bio/Bio.tsx
  src/components/sign-up-first/index.tsx
  src/hooks/useVerification.ts
  src/pages/account-verification/index.tsx
  src/pages/index.tsx
  src/pages/sign-up/index.tsx
  src/redux/api/appointmentApi.ts
  src/redux/api/routes.ts
  src/redux/rootReducer.ts
  src/redux/store.ts
Labels: good first issue

#71 Feat: agreement for Client FE
  src/components/appointments/agreement-modal/AgreementModal.tsx
  src/components/appointments/agreement-modal/styles.ts
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/appointment-drawer/hooks.ts
  src/components/appointments/appointment-drawer/styles.ts
  src/components/appointments/appointments-list/AppointmentsList.tsx
  src/components/appointments/complete-appointment-modal/CompleteAppointmentModal.tsx
  src/components/appointments/complete-appointment-modal/styles.ts
  src/components/appointments/constants.ts
  src/components/appointments/helpers.ts
  src/components/reusable/modal/Modal.tsx
  src/components/reusable/modal/styles.ts
  src/constants/index.ts
  src/locales/langs/en.ts
Labels: enhancement

#75 Features/connect agreement to backend
  src/components/appointments/agreement-modal/AgreementModal.tsx
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/appointment-status/AppointmentStatus.tsx
  src/components/appointments/appointment-status/styles.ts
  src/components/appointments/types.ts
  src/components/reusable/modal/Modal.tsx
  src/constants/index.ts
  src/redux/api/appointmentApi.ts
Labels: good first issue

#76 Features/virtual assessment by client
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/appointment-drawer/hooks.ts
  src/components/appointments/request-sent-modal/VirtualAssessmentSuccess.tsx
  src/components/appointments/request-sent-modal/styles.ts
  src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
  src/components/appointments/virtual-assessment-modal/styles.ts
  src/components/create-appointment/Appointment.tsx
  src/components/create-appointment/OneTimeAppointment.tsx
  src/constants/index.ts
  src/locales/langs/en.ts
  src/theme/typography.ts
Labels: good first issue

#77 feat: make create appointment page buttons design
  src/components/confirm-appointment/ConfirmAppointment.tsx
  src/components/confirm-appointment/TasksList.tsx
  src/components/confirm-appointment/types.ts
  src/components/create-appointment-fourth/CreateAppointmentFourth.tsx
  src/components/create-appointment-fourth/CreateAppointmentFourthDrawer.tsx
  src/components/create-appointment-fourth/drawer/styles.ts
  src/components/create-appointment/AppointmentScheduling.tsx
  src/components/create-appointment/AppointmentType.tsx
  src/components/create-appointment/OneTimeAppointment.tsx
  src/components/create-appointment/RecurringAppointment.tsx
  src/components/create-appointment/styles.ts
  src/components/health-questionnaire/index.tsx
  src/components/health-questionnaire/steps/Step1.tsx
  src/components/health-questionnaire/steps/Step2.tsx
  src/components/health-questionnaire/steps/Step3.tsx
  src/components/reusable/appointment-btn/AppointmentBtn.tsx
  src/components/reusable/appointment-btn/styles.ts
  src/pages/create-appointment/index.tsx
Labels: good first issue

#70 feat: create caregiver schedule page
  .eslintrc
  src/assets/icons/AccessTimeIcon.tsx
  src/components/book-appointment/BookAppointment.tsx
  src/components/caregiver-schedule/CaregiverAppointment.tsx
  src/components/caregiver-schedule/CaregiverSchedule.tsx
  src/components/caregiver-schedule/mocks.ts
  src/components/caregiver-schedule/styles.ts
  src/components/caregiver-schedule/types.ts
  src/components/complete-profile-second/CompleteProfileSecond.tsx
  src/components/complete-profile-third/hooks.ts
  src/components/confirm-appointment/TasksList.tsx
  src/components/create-appointment-fourth/helpers.ts
  src/components/create-appointment-fourth/places-autocomplete/CreateAppointmentFourthAutocomplete.tsx
  src/components/create-appointment/RecurringAppointment.tsx
  src/components/enter-email/hooks.ts
  src/components/example-form/index.tsx
  src/components/health-questionnaire/steps/SecondStepItem.tsx
  src/components/profile/profile-qualification/ProfileQualification.tsx
  src/components/profile/profile-qualification/certificate-form/validation.ts
  src/components/reset-password-form/ResetPasswordForm.tsx
  src/components/reusable/drawer/caregiver-drawer/helpers.ts
  src/components/reusable/header/MainHeader.tsx
  src/components/sign-up-second/hooks.ts
  src/components/sign-up-second/index.tsx
  src/components/verification/Verification.tsx
  src/components/verification/VerificationSuccess.tsx
  src/constants/index.ts
  src/hooks/useVerification.ts
  src/locales/langs/en.ts
  src/pages/index.tsx
  src/theme/colors.ts
  src/theme/fonts.ts
  src/utils/checkEmail.ts
  src/utils/formatTime.ts
Labels: good first issue

#78 feat: make api endpoint for client's virtual assessment request
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
  src/components/appointments/virtual-assessment-modal/styles.ts
  src/locales/langs/en.ts
  src/redux/api/virtualAssessmentApi.ts
Labels: good first issue

#85 feat: add get appointments by date request
  src/locales/langs/en.ts
  src/redux/api/appointmentApi.ts
  src/redux/api/routes.ts
Labels: enhancement

#83 feat: edit profile page FE, B&F
  src/assets/icons/EditSquare.tsx
  src/components/account-details/AccountDetails.tsx
  src/components/account-details/address-modal/AddressModal.tsx
  src/components/account-details/constants.ts
  src/components/account-details/personal-info-modal/PersonalInfoModal.tsx
  src/components/account-details/personal-info-modal/styles.ts
  src/components/account-details/personal-info-modal/types.ts
  src/components/account-details/personal-info-modal/validation.ts
  src/components/account-details/styles.ts
  src/components/account-details/types.ts
  src/components/account-details/validation.ts
  src/components/reusable/modal/Modal.tsx
  src/components/reusable/modal/styles.ts
  src/locales/langs/en.ts
  src/pages/account-details/index.tsx
  src/redux/api/authApi.ts
  src/redux/api/routes.ts
  src/redux/api/userApi.ts
  src/redux/store.ts
  src/routes/index.ts
Labels: good first issue

#88 feat: get help modal
  src/assets/icons/FavoriteIcon.tsx
  src/components/get-help-modal/GetHelpModal.tsx
  src/components/get-help-modal/styles.ts
  src/components/reusable/modal/styles.ts
  src/constants/index.ts
  src/locales/langs/en.ts
Labels: good first issue

#91 fix: profile layout
  src/components/reusable/profile-wrapper/styles.ts
Labels: bug

#92 fix: change min date for expiration date picker
  src/components/profile/profile-qualification/certificate-form/CertificateForm.tsx
Labels: bug

#93 fix: start date cannot be in future
  src/components/profile/profile-qualification/certificate-form/validation.ts
  src/locales/langs/en.ts
Labels: bug

#89 refactor: make reusable hook to choose start and end time
  src/components/create-appointment/OneTimeAppointment.tsx
  src/components/create-appointment/RecurringAppointment.tsx
  src/hooks/useChooseTime.ts
  src/utils/calculateTimeDifference.ts
Labels: enhancement

#90 feat: implement assessment rescheduling logic
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/appointment-drawer/hooks.ts
  src/components/appointments/request-sent-modal/VirtualAssessmentSuccess.tsx
  src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
  src/components/appointments/virtual-assessment-modal/constants.ts
  src/components/appointments/virtual-assessment-modal/enums.ts
  src/components/appointments/virtual-assessment-modal/styles.ts
  src/components/appointments/virtual-assessment-modal/useVirtualAssessmentModal.tsx
  src/components/create-appointment/Appointment.tsx
  src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
  src/components/virtual-assessment-request/styles.ts
  src/components/virtual-assessment-request/types.ts
  src/locales/langs/en.ts
  src/redux/api/virtualAssessmentApi.ts
Labels: good first issue

#99 fix: fix complete profile availability logic and styles
  src/components/complete-profile-fourth/CompleteProfileFourth.tsx
  src/components/complete-profile-fourth/hooks.ts
  src/components/complete-profile-fourth/styles.ts
Labels: bug

#100 fix: adjust main header logic
  src/components/appointments/AppointmentsPage.tsx
  src/components/caregiver-schedule/CaregiverSchedulePage.tsx
  src/components/reusable/header/MainHeader.tsx
  src/components/reusable/header/enums.ts
  src/components/reusable/header/styles.ts
  src/pages/account-details/index.tsx
  src/routes/index.ts
Labels: enhancement

#105 fix: fix custom tasks deletion logic
  src/components/confirm-appointment/TasksList.tsx
Labels: bug

#103 fix: change logic to open caregiver drawer on confirm appointment step
  src/components/confirm-appointment/ConfirmAppointment.tsx
  src/components/create-appointment-fourth/CreateAppointmentFourthDrawer.tsx
Labels: bug

#108 fix: add trim for string fields
  src/components/account-details/personal-info-modal/validation.ts
  src/components/complete-profile-second/work-form/validation.ts
  src/components/login-form/validation.ts
  src/components/profile/bio/validation.ts
  src/components/profile/profile-qualification/certificate-form/validation.ts
  src/components/reset-password-form/validation.ts
  src/components/sign-up-second/validation.ts
Labels: bug

#96 fix: rename error for invalid date format
  src/components/profile/profile-qualification/certificate-form/CertificateForm.tsx
  src/components/profile/profile-qualification/certificate-form/constants.ts
  src/components/profile/profile-qualification/certificate-form/validation.ts
  src/locales/langs/en.ts
Labels: bug

#106 fix: updated langs, sign up validation
  src/components/sign-up-third/validation.ts
  src/constants/index.ts
  src/locales/langs/en.ts
Labels: bug

#107 fix: update constants, date picker
  src/components/complete-profile-second/work-form/WorkForm.tsx
  src/components/complete-profile-second/work-form/constants.ts
  src/components/complete-profile-second/work-form/validation.ts
Labels: bug

#110 fix: add complete profile services validation
  src/components/complete-profile-third/CompleteProfileThird.tsx
  src/components/complete-profile-third/validation.ts
Labels: bug

#109 fix: transitions
  src/components/complete-profile-fourth/hooks.ts
  src/components/private-route/PrivateRoute.tsx
  src/components/profile/bio/Bio.tsx
  src/components/reusable/drawer/caregiver-drawer/CaregiverDrawer.tsx
  src/components/sendOTP/SuccessfulVerification.tsx
  src/hooks/useVerification.ts
  src/locales/langs/en.ts
  src/pages/account-verification/index.tsx
  src/redux/api/accountVerificationAPI.ts
  src/redux/api/profileCompleteApi.ts
  src/redux/slices/userSlice.ts
  src/routes/index.ts
Labels: bug

#95 fix: add validation for expiration date field
  src/components/profile/profile-qualification/certificate-form/constants.ts
  src/locales/langs/en.ts
Labels: bug

#113 fix: remove unused constants file
  src/components/private-route/constants.ts
Labels: bug

#114 fix: fix date bugs connected to user setting past date
  src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
  src/components/appointments/virtual-assessment-modal/useVirtualAssessmentModal.tsx
  src/components/create-appointment/OneTimeAppointment.tsx
  src/components/create-appointment/RecurringAppointment.tsx
  src/locales/langs/en.ts
Labels: bug

#115 fix: reset all appointment info after it has been created
  src/components/confirm-appointment/ConfirmAppointment.tsx
  src/redux/slices/healthQuestionnaireSlice.ts
Labels: bug

#111 feat: add Logout on Complete profile page
  src/components/log-out-modal/LogOutModal.tsx
  src/components/log-out-modal/styles.ts
  src/components/reusable/header/FlowHeader.tsx
  src/components/reusable/header/styles.ts
  src/locales/langs/en.ts
  src/redux/slices/userSlice.ts
Labels: bug

#97 feat: create 'update password' component
  __tests__/update-password/UpdatePassword.tsx
  src/components/account-details/AccountDetails.tsx
  src/components/account-details/update-password-form/UpdatePassword.tsx
  src/components/account-details/update-password-form/UpdatePasswordSuccess.tsx
  src/components/account-details/update-password-form/styles.ts
  src/components/account-details/update-password-form/validation.ts
  src/constants/index.ts
  src/locales/langs/en.ts
  src/redux/api/routes.ts
  src/redux/api/userApi.ts
Labels: good first issue

#117 fix: agreement modal height
  src/components/appointments/agreement-modal/styles.ts
Labels: bug
