Repository ZenBit-Tech/ctrlchamps_fe, pull requests merged in 2024-01, with the labels that each got.

#116 fix: cancel appointment modal
  src/components/appointments/appointment-drawer/hooks.ts
Labels: bug

#121 feat: create caregiver profile
  src/components/caregiver-info/CaregiverInfo.tsx
  src/components/caregiver-info/caregiver-info-section/CaregiverInfoSection.tsx
  src/components/caregiver-info/caregiver-info-section/styles.ts
  src/components/caregiver-info/hooks.tsx
  src/components/caregiver-info/styles.ts
  src/components/complete-profile-second/styles.ts
  src/components/complete-profile-second/work-list/styles.ts
  src/components/profile/profile-qualification/ProfileQualification.tsx
  src/components/profile/profile-qualification/certificate-list/styles.ts
  src/components/profile/profile-qualification/styles.ts
  src/components/reusable/header/Menu.tsx
  src/components/reusable/modal/Modal.tsx
  src/components/reusable/modal/styles.ts
  src/config-global.ts
  src/constants/enums.ts
  src/locales/langs/en.ts
  src/pages/caregiver-profile/index.tsx
  src/redux/api/appointmentApi.ts
  src/routes/index.ts
  src/theme/colors.ts
  src/types/Caregiver.type.ts
Labels: enhancement

#123 fix: need help & get help modals
  src/components/get-help-modal/GetHelpModal.tsx
  src/components/modal-need-help/NeedHelpModal.tsx
  src/components/reusable/header/Menu.tsx
Labels: bug

#124 fix: Complete profile 3,5
  src/components/complete-profile-fifth/CompleteProfileFifth.tsx
  src/components/complete-profile-third/CompleteProfileThird.tsx
Labels: bug

#119 Fix/account verification fields
  src/components/sendOTP/AccountVerification.tsx
  src/components/sendOTP/DigitInputField.tsx
  src/components/sendOTP/styles.ts
  src/components/verification/OTPInput.tsx
  src/components/verification/Verification.tsx
  src/components/verification/constants.ts
  src/constants/index.ts
  src/utils/focusOnNextElement.ts
Labels: bug

#122 fix: remove styles from faq page
  src/components/faq-accordion/FaqAccordion.tsx
  src/components/faq-accordion/styles.ts
  src/pages/faq/index.tsx
  src/theme/overrides/Accordion.ts
Labels: bug

#128 fix: fix one-time appointment logic
  src/components/create-appointment/OneTimeAppointment.tsx
  src/locales/langs/en.ts
Labels: enhancement

#126 fix: update avatar button text
  src/components/account-details/AccountDetails.tsx
  src/components/account-details/styles.ts
  src/locales/langs/en.ts
Labels: bug

#127 fix: updated button's styles in appointment request
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/appointment-drawer/styles.ts
  src/locales/langs/en.ts
Labels: bug

#132 feat: add avatar from db to all components
  src/components/account-details/AccountDetails.tsx
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/appointment-drawer/styles.ts
  src/components/appointments/complete-appointment-modal/CompleteAppointmentModal.tsx
  src/components/appointments/constants.ts
  src/components/appointments/helpers.ts
  src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
  src/components/caregiver-schedule/CaregiverAppointment.tsx
  src/components/caregiver-schedule/styles.ts
  src/components/confirm-appointment/ConfirmAppointment.tsx
  src/components/create-appointment-fourth/CreateAppointmentFourth.tsx
  src/components/create-appointment-fourth/constants.ts
  src/components/create-appointment-fourth/helpers.ts
  src/components/create-appointment-fourth/styles.ts
  src/components/reusable/drawer/caregiver-drawer/CaregiverDrawer.tsx
  src/components/reusable/drawer/caregiver-drawer/constants.ts
  src/components/reusable/drawer/caregiver-drawer/styles.ts
  src/components/reusable/header/MainHeader.tsx
  src/components/reusable/user-avatar/UserAvatar.tsx
  src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
  src/constants/index.ts
  src/redux/api/userApi.ts
Labels: enhancement

#131 fix: create custom hook for trimming input spaces
  src/components/account-details/update-password-form/UpdatePassword.tsx
  src/hooks/useCustomForm.ts
Labels: bug

#133 fix: fix custom tasks deleting logic + add invalidation tag for creat…
  src/components/confirm-appointment/TasksList.tsx
  src/redux/api/appointmentApi.ts
Labels: bug

#143 fix: avatar button
  src/components/account-details/styles.ts
Labels: bug

#134 refactor: refactor virtual assessment logic
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/virtual-assessment-modal/useVirtualAssessmentModal.tsx
  src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
  src/redux/api/appointmentApi.ts
  src/redux/api/virtualAssessmentApi.ts
Labels: enhancement

#142 fix: updated user age validation
  src/components/sign-up-second/index.tsx
  src/components/sign-up-second/validation.ts
  src/locales/langs/en.ts
Labels: bug

#140 fix: work experience date validation
  src/components/complete-profile-second/work-form/WorkForm.tsx
  src/components/complete-profile-second/work-form/validation.ts
  src/locales/langs/en.ts
Labels: bug

#141 feat: create and connect user roles list
  src/components/admin-management/AdminManagement.tsx
  src/components/admin-management/constants.ts
  src/components/admin-management/styles.ts
  src/components/admin-menu/AdminMenu.tsx
  src/components/admin-menu/constants.ts
  src/components/admin-menu/styles.ts
  src/components/admin-menu/types.ts
  src/components/caregiver-info/CaregiverInfo.tsx
  src/hooks/useDebounce.ts
  src/locales/langs/en.ts
  src/pages/admin-panel/admin-management/index.tsx
  src/redux/api/adminPanelAPI.ts
  src/redux/api/routes.ts
  src/redux/api/userApi.ts
  src/redux/store.ts
  src/routes/index.ts
  src/theme/colors.ts
Labels: enhancement

#138 feat: create notifications list ui and api
  src/assets/icons/SignatureIcon.tsx
  src/components/notifications-list/Notification.tsx
  src/components/notifications-list/NotificationsList.tsx
  src/components/notifications-list/constants.ts
  src/components/notifications-list/styles.ts
  src/locales/langs/en.ts
  src/pages/notifications/index.tsx
  src/redux/api/notificationsApi.ts
  src/redux/api/routes.ts
  src/redux/store.ts
  src/theme/colors.ts
Labels: good first issue

#148 fix: fix time and link validation
  src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
  src/components/appointments/virtual-assessment-modal/useVirtualAssessmentModal.tsx
  src/components/create-appointment/OneTimeAppointment.tsx
  src/components/create-appointment/RecurringAppointment.tsx
  src/constants/index.ts
  src/locales/langs/en.ts
  src/utils/checkTime.ts
Labels: bug

#146 feat: User list BF
  src/components/account-details/AccountDetails.tsx
  src/components/account-details/styles.ts
  src/components/admin-management/AdminManagement.tsx
  src/components/login-form/LoginForm.tsx
  src/components/user-list/UserList.tsx
  src/components/user-list/constants.ts
  src/components/user-list/mocks.ts
  src/components/user-list/styles.ts
  src/components/user-list/types.ts
  src/constants/index.ts
  src/locales/langs/en.ts
  src/pages/account-details/[id].tsx
  src/pages/admin-panel/account-details/[id].tsx
  src/pages/admin-panel/index.tsx
  src/redux/api/userApi.ts
  src/routes/index.ts
Labels: enhancement

#152 fix: fix confirm password bug
  src/components/account-details/update-password-form/UpdatePassword.tsx
Labels: bug

#153 fix: expiration date can be set earlier than today
  src/components/profile/profile-qualification/certificate-form/CertificateForm.tsx
  src/components/profile/profile-qualification/certificate-form/validation.ts
  src/locales/langs/en.ts
Labels: bug

#154 feat: add notifications
  package-lock.json
  src/components/notifications-list/constants.ts
  src/locales/langs/en.ts
  yarn.lock
Labels: enhancement

#156 feat: refetch data on window focus
  src/redux/api/activityLogApi.ts
  src/redux/api/appointmentApi.ts
  src/redux/api/notificationsApi.ts
  src/redux/api/virtualAssessmentApi.ts
  src/redux/store.ts
Labels: enhancement

#149 feat: create tasks list and connect api
  src/components/admin-appointment-list/AppointmentList.tsx
  src/components/admin-management/tasks/TaskRow.tsx
  src/components/admin-management/tasks/TasksManagement.tsx
  src/components/admin-management/tasks/constants.ts
  src/components/admin-management/tasks/modals/AddModal.tsx
  src/components/admin-management/tasks/modals/DeleteModal.tsx
  src/components/admin-management/tasks/modals/EditModal.tsx
  src/components/admin-menu/constants.ts
  src/components/confirm-appointment/TasksList.tsx
  src/components/confirm-appointment/constants.ts
  src/components/reusable/popup/Popup.tsx
  src/constants/index.ts
  src/locales/langs/en.ts
  src/pages/admin-panel/task-management/index.tsx
  src/redux/api/routes.ts
  src/redux/api/tasksApi.ts
  src/redux/store.ts
  src/routes/index.ts
Labels: good first issue

#159 fix: removed drawer_buttons for admins, added greenspan for role
  src/components/admin-appointment-list/AppointmentList.tsx
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/user-list/UserList.tsx
Labels: bug

#163 feat: change style logic
  src/components/appointments/appointments-list/AppointmentsList.tsx
  src/components/appointments/appointments-list/styles.ts
  src/components/caregiver-schedule/CaregiverAppointment.tsx
  src/components/caregiver-schedule/CaregiverSchedule.tsx
  src/components/caregiver-schedule/CaregiverSchedulePage.tsx
  src/components/caregiver-schedule/styles.ts
  src/components/notifications-list/constants.ts
  src/components/reusable/header/MainHeader.tsx
  src/components/reusable/header/Menu.tsx
  src/components/reusable/header/styles.ts
  src/locales/langs/en.ts
  src/redux/api/notificationsApi.ts
Labels: enhancement

#164 feat: add pagination for notifications and transactions
  src/components/notifications-list/NotificationsList.tsx
  src/components/notifications-list/constants.ts
  src/components/transactions/TransactionsModal.tsx
  src/components/transactions/constants.ts
  src/components/transactions/styles.ts
  src/constants/index.ts
  src/pages/notifications/index.tsx
  src/pages/transactions/index.tsx
  src/redux/api/notificationsApi.ts
  src/redux/api/transactionsApi.ts
  src/redux/store.ts
Labels: good first issue

#162 feat: Notifications displaying
  src/components/reusable/header/MainHeader.tsx
  src/pages/notifications/index.tsx
  src/redux/api/notificationsApi.ts
  src/redux/api/routes.ts
Labels: enhancement

#160 feat: update caregiver shedule
  src/components/caregiver-schedule/CaregiverAppointment.tsx
  src/components/caregiver-schedule/types.ts
  src/constants/index.ts
Labels: enhancement

#168 feat: add approved/rejected activity logs columns
  src/components/admin-appointment-list/AppointmentList.tsx
  src/components/admin-appointment-list/styles.ts
  src/components/appointments/types.ts
  src/locales/langs/en.ts
Labels: enhancement

#169 fix: fix virtual assessment modal logic
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/virtual-assessment-modal/VirtualAssessmentModal.tsx
  src/components/appointments/virtual-assessment-modal/useVirtualAssessmentModal.tsx
  src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
  src/locales/langs/en.ts
Labels: bug

#170 fix: fix transactions pagination
  src/components/account-details/AccountDetails.tsx
  src/components/transactions/TransactionsModal.tsx
  src/pages/transactions/index.tsx
  src/redux/api/transactionsApi.ts
Labels: bug

#166 fix: Caregiver can't accept an expired VA request
  src/components/caregiver-schedule/CaregiverAppointment.tsx
  src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
Labels: enhancement

#172 fix: fixed layout in adming-page, added name column to appointments list
  src/components/account-details/styles.ts
  src/components/admin-appointment-list/AppointmentList.tsx
  src/components/user-list/styles.ts
  src/locales/langs/en.ts
  src/pages/admin-panel/admin-management/index.tsx
Labels: bug

#174 fix: add text when admins array is empty
  src/components/admin-management/AdminManagement.tsx
Labels: bug

#171 fix: admin delete modal
  src/components/admin-management/AdminManagement.tsx
  src/components/user-list/UserList.tsx
  src/pages/admin-panel/account-details/[id].tsx
Labels: bug

#175 fix: delet modal user list
  src/components/account-details/AccountDetails.tsx
  src/components/admin-management/AdminManagement.tsx
  src/components/user-list/UserList.tsx
Labels: bug

#176 fix: date format in VA request
  src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
Labels: bug

#177 feat: transactions pagination(edit user by admin)
  src/components/account-details/AccountDetails.tsx
  src/components/account-details/constants.ts
Labels: enhancement

#183 fix: VA time now displayed in local time, not in appointments time
  src/components/appointments/virtual-assessment-modal/helpers.ts
  src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
Labels: bug

#184 fix: reset token if user inactive or deleted
  src/components/private-route/PrivateRoute.tsx
  src/pages/account-verification/index.tsx
  src/pages/admin-panel/task-management/index.tsx
  src/pages/faq/index.tsx
  src/pages/index.tsx
  src/pages/notifications/index.tsx
  src/pages/sign-up/index.tsx
  src/pages/transactions/index.tsx
Labels: bug

#186 Feat: caregiver reviews
  src/components/reusable/drawer/caregiver-drawer/CaregiverDrawer.tsx
  src/components/reusable/drawer/caregiver-drawer/constants.ts
  src/components/reusable/drawer/caregiver-drawer/styles.ts
  src/locales/langs/en.ts
  src/types/Caregiver.type.ts
Labels: enhancement

#187 feat: create caregiver review modal
  src/components/appointments/appointments-list/AppointmentsList.tsx
  src/components/reusable/drawer/caregiver-drawer/CaregiverDrawer.tsx
  src/components/reusable/drawer/caregiver-drawer/styles.ts
  src/components/review-modal/ReviewModal.tsx
  src/components/review-modal/constants.ts
  src/components/review-modal/styles.ts
  src/components/review-modal/validation.ts
  src/locales/langs/en.ts
  src/redux/api/reviewApi.ts
  src/redux/api/routes.ts
  src/redux/store.ts
Labels: enhancement

#191 fix: bug fix
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
Labels: bug

#189 feat: add warning for appointment creation in 6 hours
  src/components/confirm-appointment/ConfirmAppointment.tsx
  src/components/create-appointment/AppointmentScheduling.tsx
  src/components/create-appointment/AppointmentType.tsx
  src/components/create-appointment/OneTimeAppointment.tsx
  src/components/create-appointment/PaymentNotification.tsx
  src/components/create-appointment/RecurringAppointment.tsx
  src/components/create-appointment/constants.ts
  src/components/create-appointment/styles.ts
  src/components/modal-cancel-appointment/CancelAppointmentModal.tsx
  src/locales/langs/en.ts
  src/redux/slices/appointmentSlice.ts
  src/theme/colors.ts
Labels: enhancement

#192 fix: fix type errors
  src/components/reusable/drawer/caregiver-drawer/CaregiverDrawer.tsx
  src/redux/api/appointmentApi.ts
Labels: bug

#190 feat: show appointment in calendar only if it is appointment date
  src/components/appointments/appointment-drawer/AppointmentDrawer.tsx
  src/components/appointments/appointment-drawer/hooks.ts
  src/components/caregiver-schedule/CaregiverSchedule.tsx
Labels: enhancement

#193 fix: fixed error which led to displaying wrong time for VA
  src/components/caregiver-schedule/CaregiverAppointment.tsx
  src/components/virtual-assessment-request/VirtualAssessmentRequest.tsx
  src/utils/formatTime.ts
Labels: bug

#194 fix: work hours for recurring appointment
  src/components/appointments/agreement-modal/AgreementModal.tsx
  src/components/appointments/agreement-modal/helpers.ts
  src/constants/index.ts
  src/redux/api/appointmentApi.ts
Labels: bug

#195 fix: fix date for seeker's appointments
  src/components/appointments/appointment-drawer/hooks.ts
Labels: bug

#197 fix: fixed reschedule time error
  src/components/appointments/virtual-assessment-modal/useVirtualAssessmentModal.tsx
Labels: bug
